# Generated by Django 5.1.6 on 2025-02-14 20:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_optimization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceOptimizationProcess',
            new_name='Process',
        ),
        migrations.RenameModel(
            old_name='ResourceOptimizationIAAnalysis',
            new_name='ResultAnalysis',
        ),
    ]
