# Generated by Django 5.1.6 on 2025-02-17 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_integration', '0001_initial'),
        ('resource_optimization', '0002_rename_resourceoptimizationprocess_process_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.TextField()),
                ('result_data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('llm_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='llm_integration.llmrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AvailableLLM',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='EndpointCost',
        ),
        migrations.RemoveField(
            model_name='process',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resultanalysis',
            name='process',
        ),
        migrations.RemoveField(
            model_name='tokenusage',
            name='process',
        ),
        migrations.RemoveField(
            model_name='tokenusage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercredits',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='resultanalysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='resultanalysis',
            old_name='explanation',
            new_name='analysis_text',
        ),
        migrations.RemoveField(
            model_name='resultanalysis',
            name='result_data',
        ),
        migrations.AddField(
            model_name='resultanalysis',
            name='ai_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultanalysis',
            name='llm_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='llm_integration.llmrequest'),
        ),
        migrations.AlterField(
            model_name='resultanalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='resultanalysis',
            name='optimization_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='resource_optimization.optimizationprocess'),
        ),
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='TokenUsage',
        ),
        migrations.DeleteModel(
            name='UserCredits',
        ),
    ]
