# Generated by Django 5.1.6 on 2025-02-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_optimization', '0003_optimizationprocess_delete_availablellm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationprocess',
            name='credit_cost',
            field=models.IntegerField(),
        ),
    ]
